### ISSUE TITLE
How to send inline image in mail.

### ISSUE THREAD

**Issue by darshit7** [dstegelman/django-mail-queue#104]
Hi,
I want to include inline images in mail template (not as an attachment).
It is supported?

**Comment by Goury** [comment]
You are definitely doing it wrong
The point of this application is in absolutely different area

**Comment by dstegelman** [comment]
Hi @darshit7 ,

You could certainly embed an image by referencing it in an html image tag, but this library does not support directly embedding media in the mail message itself.  Off the top of my head I'm not sure of a Django library that does this either, though I could certainly be wrong.
