### ISSUE TITLE
Getting Warning: mailqueue.models.MailerMessage doesn't declare an explicit app_label

### ISSUE THREAD

**Issue by nielsonsantana** [dstegelman/django-mail-queue#109]
My setup: django version 1.8, Python 2.7
Every time I run my django application, I saw this warning: 

`WARNING /usr/local/lib/python2.7/site-packages/mailqueue/models.py:40: RemovedInDjango19Warning: Model class mailqueue.models.MailerMessage doesn't declare an explicit app_label and either isn't in an application in INSTALLED_APPS or else was imported before its application was loaded. This will no longer be supported in Django 1.9.`

**Comment by dstegelman** [comment]
Thanks for reporting, any desire to put in a pull request to address this?

**Comment by dstegelman** [comment]
As I have not found a maintainer, I'm going to be arching this repository as I can no longer maintain it.  You are more than welcome to fork and address this issue.
