### ISSUE TITLE
Not working with MAILQUEUE_CELERY = True

### ISSUE THREAD

**Issue by DmitryNoven** [dstegelman/django-mail-queue#112]
Probably because of call to protected func in tasks.py:
```
@shared_task(name="tasks.send_mail", default_retry_delay=5, max_retries=5)
def send_mail(pk):
    message = MailerMessage.objects.get(pk=pk)
    message._send()

    # Retry when message is not sent
    if not message.sent:
        send_mail.retry([message.pk])
```

**Comment by dstegelman** [comment]
Thanks for reporting, would you like to submit a PR?

**Comment by dstegelman** [comment]
As I have not found a maintainer, I'm going to be arching this repository as I can no longer maintain it.  You are more than welcome to fork and address this issue.
