### ISSUE TITLE
Help using django-mail-queue

### ISSUE THREAD

**Issue by thisisfun** [dstegelman/django-mail-queue#57]
I am a newbie in Django. It would be great if you could point me to a link which talks about the prior configurations required before I use your package.
An example how your package is used can help greatly

Thank you

**Comment by dstegelman** [comment]
The [documentation](https://django-mail-queue.readthedocs.org/en/latest/index.html) is a great place to start if you are talking specifically about setting up this package.  Install it and then take a look at usage.  It's important to note that you will need to make sure to setup your django environment to send mail, which means setting things like [email settings](https://docs.djangoproject.com/en/1.8/ref/settings/#email-host)

Personally, Ive been able to set this up with Gmail or some other provider.  Setting those parts up and making sure email is working is outside the scope of what I can answer of you here though, you might try your hand at Google if you need more in depth tutorials.

If there is something specific to this library that is unclear you can add issues here and we can clear those things up in our documentation.

**Comment by thisisfun** [comment]
Thank You! I was able to setup email settings and use your package! Thanks
