### ISSUE TITLE
Add priority level

### ISSUE THREAD

**Issue by juliosmelo** [dstegelman/django-mail-queue#63]
The messages can have a priority level such as 'low', 'medium', 'high'. We can use this in management command like this.

python manage.py send_queued_messages --priority=low
python manage.py send_queued_messages --priority=medium
python manage.py send_queued_messages --priority=hight

**Comment by dstegelman** [comment]
How would this work with the auto/celery based sending of messages? Queue them up in order? I'm not really sure that this is something necessary for this library.  Can you provide a general use case?
