### ISSUE TITLE
Email not sending

### ISSUE THREAD

**Issue by ajeebkp23** [dstegelman/django-mail-queue#70]
Hi,

I was the one to embrace your idea ( of course your hard work) for some of our work. Thanks for such a brilliant work.

I was testing things against actual data (using client's data). Since, we are a small team and doesn't have a staging server and all, we do it in local.

But, my question is, how should delete existing mail queue entries?
Is `MailerMessage.objects.all().delete()` a right way to do it? (I know there is a `python manage.py clear_sent_messages`, but i didn't used it at first)

I tried this one first `MailerMessage.objects.all().delete()` . And then i tried to send mail (after changing some mail ids and all with Django querysets, and  of course creating some emails),  with `python manage.py send_queued_messages`.

Then, emails were not sending. I doubted the my django settings, so I tried changing and all.

During these actions I never used `python manage.py clear_sent_messages`.

After those repeated failures, i tried `python manage.py clear_sent_messages`. Boom! Now it works like a charm (after creating new emails). Is it a bug? Or where I am wrong?

**Comment by dstegelman** [comment]
@ajeebkp23 are you using Celery?  

```MailerMessage.objects.all().delete()``` will delete existing entries. 

```clear_sent_messages``` will remove records that have been marked as sent.  Its not really required to do this, but it can help in keeping the mail db a little less large.

I'm not really sure what happened in your case.  Perhaps there were just too many emails and a failure was preventing it from working.  It doesn't sound to me like there is a bug here, but if you run into more issues, please let me know.

**Comment by ajeebkp23** [comment]
I too think some thing external. Today, morning I found a bunch of emails in my inbox (which I had used for testing) .

I was using from command itself (for development purpose). I am closing this issue since it doesn't make sense as a bug.
