### ISSUE TITLE
delete the sent messages!

### ISSUE THREAD

**Issue by amournet** [dstegelman/django-mail-queue#71]
how can i delete the sent messages!! or i have to make a cron to delete !!

**Comment by dstegelman** [comment]
It is not documented, but you can clear them using a management command.

https://github.com/dstegelman/django-mail-queue/blob/master/mailqueue/management/commands/clear_sent_messages.py

```
./manage.py clear_sent_messages --offset=<youroffeset>
```

I'll add an issue to document this behavior.
