### ISSUE TITLE
AttributeError: type object 'BaseCommand' has no attribute 'option_list'

### ISSUE THREAD

**Issue by dstegelman** [dstegelman/django-mail-queue#79]
AttributeError: type object 'BaseCommand' has no attribute 'option_list'

**Comment by abidibo** [comment]
as a workaround I've created another management command inside my app, which uses the [add_argument](https://docs.djangoproject.com/en/1.9/howto/custom-management-commands/#accepting-optional-arguments) method of BaseCommand

    from django.core.management.base import BaseCommand

    from mailqueue.models import MailerMessage


    class Command(BaseCommand):
        help = 'Can be run as a cronjob or directly to send queued messages.'

        def add_arguments(self, parser):

            # Named (optional) arguments
            parser.add_argument(
                '--limit',
                action='store',
                dest='limit',
                help='Limit the number of emails to process',
            )

        def handle(self, *args, **options):
            MailerMessage.objects.send_queued(limit=options['limit'])

**Comment by dstegelman** [comment]
Yeah this is due to not supporting 1.10 yet.  I've been really busy lately and haven't tied everything up yet.  Will probably get to this in the next few weeks.
