### ISSUE TITLE
Storing attachments in media_root is super insecure and just wrong

### ISSUE THREAD

**Issue by Goury** [dstegelman/django-mail-queue#80]
Issue 1: attachment is confidential but if webserver is configured to serve media, anyone can just point browser to media/mail-queue/attachments/what.ever and just download it. If not, attachment will not work for admin.

Issue 2: so I generated unique image.png for each of 65536 of my good users. Nope, they all got the same last one and everything else is just gone.

Proposed solution:
Store files in custom location which is not served by default and use some prefixes for files, at least by crc. Because instead of filesystem, email message can have multiple files with the same name attached to it.

UPD: somehow attachments isn't removed from filesystem on message deletion. This sounds just wrong. I will try to fix this issue too.

**Comment by dstegelman** [comment]
Thanks for reporting these issues, if you'd like you can submit a pull request, but otherwise, I work on this on my spare time, and right now that is very limited.

**Comment by Goury** [comment]
It seems I have to fix this myself.

Ill submit pull request as soon as I do everything but I prefer GNU AGPL v3 license.
I will submit it on current terms this time but please consider changing it to something less indifferent.

**Comment by Goury** [comment]
UPD: somehow attachments isn't removed from filesystem on message deletion. This sounds just wrong. I will try to fix this issue too.

**Comment by Goury** [comment]
@dstegelman 
Please mark this issue as critical bug, GitHub won't let me do so.

**Comment by dstegelman** [comment]
While I appreciate the prepared fix, the attitude associated with issue is not really appropriate.  In the future, I'd appreciate less condescending language in **_my_** projects.

**Comment by Goury** [comment]
@dstegelman 
Seems there is a flaw in my code, I am currently working on project related to and depended on django-mail-queue so I will fix it soon.

**Comment by Goury** [comment]
It looks like flaw is compensated

**Comment by dstegelman** [comment]
Merged
