### ISSUE TITLE
add_attachment assumes it's always a file on the filesystem

### ISSUE THREAD

**Issue by dinopetrone** [dstegelman/django-mail-queue#87]
There is no way to create a text based attachment like an ICS file when using this lib.  Ideally you could do something like this:

```
from django.core.files.base import ContentFile
msg.add_attachment(ContentFile('<ics string here>'))
```

add_attachment would then check what it was being sent and save the string value when running the attachment creation.  This would likely require an additional field on the Attachment model to hold the string attachment.  Alternatively you could add a StringAttachment model and add_string_attachment method.  I'm open to doing the code myself, i would just like to know which direction would be preferred.

**Comment by dstegelman** [comment]
I'm more comfortable with creating an additional field on an existing module rather than creating a new model.

**Comment by blodone** [comment]
i have had another problem also with an additional file field but S3 storage in this field so i created #103

**Comment by dstegelman** [comment]
As I have not found a maintainer, I'm going to be arching this repository as I can no longer maintain it.  You are more than welcome to fork and address this issue.
