### ISSUE TITLE
Attachments not removed after django testing

### ISSUE THREAD

**Issue by Goury** [dstegelman/django-mail-queue#88]
So I do `manage.py test` for my django project with DMQ app installed and attachments created during testing is still in file system (because I do test some email features).
I am not sure what to do, yet DMQ should somehow clean up everything after testing is done.

Or should I just write the tests the way it cleans up for DMQ?

**Comment by dstegelman** [comment]
Django Mail queue should probably do some cleanup within its own tests make sure not to leave anything behind.

**Comment by dstegelman** [comment]
As I have not found a maintainer, I'm going to be arching this repository as I can no longer maintain it.  You are more than welcome to fork and address this issue.
