### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by aashishsoni** [dstegelman/django-mail-queue#91]
Hello,
I have setup django mail queue as written in the docs but at the time of sending mails with MAILQUEUE_CELERY = True, I am getting this error : No connection could be made because the target machine actively refused it

**Comment by dstegelman** [comment]
This sounds like an issue with how you have [celery](http://www.celeryproject.org/) setup and not likely to do with mail-queue.
