### ISSUE TITLE
Management commands not working

### ISSUE THREAD

**Issue by martinjobb** [dstegelman/django-mail-queue#92]
**When I run:**

```python manage.py send_queued_messages --limit=20```

I get this error: 

```manage.py send_queued_messages: error: argument --limit: ignored explicit argument '20'```

**When I run:** 

```python manage.py send_queued_messages```

I get this error:

```manage.py send_queued_messages: error: too few arguments```

**Comment by Goury** [comment]
Works just fine for me on my fork, haven't tried main branch yet

**Comment by dstegelman** [comment]
Thanks for reporting, I can't take a look now, but later tonight or tomorrow I should have time.

**Comment by martinjobb** [comment]
I run 3.0.0

**Comment by dstegelman** [comment]
Yeah, I can reproduce this issue.  I'll spend some time with it this week.

**Comment by dstegelman** [comment]
This has been fixed, and documentation updated. Management command should be invoked:

```
python manage.py send_queued_messages 20
```
